//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rafa27silva
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblArabalar
    {
        public int id { get; set; }
        public Nullable<int> marka { get; set; }
        public Nullable<int> model { get; set; }
        public string renk { get; set; }
        public Nullable<double> fiyat { get; set; }
        public Nullable<bool> durum { get; set; }
        public Nullable<int> modelYili { get; set; }
    
        public virtual TblMarka TblMarka { get; set; }
        public virtual TblModeller TblModeller { get; set; }
    }
}
